### ISSUE TITLE
About training and testing on the HO3D dataset

### ISSUE THREAD

**Issue by hxwork** [christsa/dgrasp#13]
Hi,

Thanks for your awesome work and code! I noticed that you also train and test the model on the HO3D dataset, however, there is no information for HO3D in the README. So how to test the model on HO3D?

**Comment by christsa** [comment]
Hi,

Thanks for your interest in our work! Note that the HO3D objects are a subset of the YCB objects - you can see in the objects marked in the supplementary of the paper (such as in Table 9). To report results for HO3D object set, we computed the average over this subset.

We perform experiments on the HO3D object set by using predictions from GraspTTA and with an image based pose estimator:

- The grasp labels we ran with GraspTTA are available in [this](https://github.com/christsa/dgrasp/blob/main/raisimGymTorch/raisimGymTorch/data/dexycb_grasptta_train.pkl) train file and [this ](https://github.com/christsa/dgrasp/blob/main/raisimGymTorch/raisimGymTorch/data/dexycb_grasptta_test.pkl) test file.

- The grasp labels we ran with HO3D images are available in [this](https://github.com/christsa/dgrasp/blob/main/raisimGymTorch/raisimGymTorch/data/contact_opt_train.pkl) train file and [this ](https://github.com/christsa/dgrasp/blob/main/raisimGymTorch/raisimGymTorch/data/contact_opt_test.pkl) test file.

If you want the test the experiments you also need to adjust the file path in the runner.py file you are using, for example as [here](https://github.com/christsa/dgrasp/blob/1653b459334dccc73a4556034b1325a6191a7b37/raisimGymTorch/raisimGymTorch/env/envs/dgrasp/runner.py#L101C1-L105).

The data is slightly different from the experiment that uses DexYCB, so there needs to be some additional changes. I currently don't have the time because of a deadline to write a clean wrapper. I added a raw file from the time of submission that contains a loader for the data [here].(https://github.com/christsa/dgrasp/blob/main/raisimGymTorch/raisimGymTorch/helper/runner_gtta.py)

Let me know if you have any more questions.
