### ISSUE TITLE
A question about the paper

### ISSUE THREAD

**Issue by xiaohao9999** [christsa/dgrasp#16]
Hello, thank you for your work.

In Section 3.1 of the paper, I want to know why 45 actuators are needed? Isn’t the degree of freedom of the hand generally 27?

![image](https://github.com/christsa/dgrasp/assets/146507142/cba0cf04-464b-424e-9fb1-8cd677a3ffe0)

**Comment by sammychristen** [comment]
Hi,

It's a good question. The reason why we use 45 DoF instead of the actual DoF of the human hand is because we model the hand based on the MANO hand model, where each joint has 3 DoF and the rotation axes are not exactly aligned with the anatomical axes of the human hand. In the meantime, there is a MANO model that is aligned with the anatomical structure of the hand [here](https://github.com/lixiny/manotorch). Aligning the hand in our simulation with an anatomical model and thereby reducing the DoFs would likely speed up the learning process and potentially further remove unnatural poses. 

Let me know if this clears things up for you.

Best,
Sammy

**Comment by xiaohao9999** [comment]
Hi, 

I think I know. Excluding the wrist, the hand model is modeled as 3 joints per finger and 3 DoF per joint. 
Then the sum of DoF is: `5 * 3 * 3 = 45`.
![image](https://github.com/christsa/dgrasp/assets/146507142/cffc24d2-5313-4029-9bc9-1328d30dd6eb)

**Comment by sammychristen** [comment]
That is what I said, yes.

Can you close the issue if it is clear? Thanks.

**Comment by xiaohao9999** [comment]
Of course. Thank you for your kind help! ;)
